### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by KostyaEsmukov** [geopy/geopy#267]
If you have any ideas – feel free to join the discussion. This is largely based on my own vision of the project and a glimpse look at the open issues and PRs.

The reason I'm writing this up is because I'm still struggling to catch up on the open issues, so having a plan in a single list makes it simpler. Eventually this list should be converted to individual issues.

Any help here is really appreciated!

- [x] Make the project more contributing-friendly
  - [x] (#266) Replace nosetest with pytest.
  - [x] ~~Split tests to two sets: unit and integration. I suppose that this would simplify local development significantly, but it would affect most of the open PRs, so this won't be soon.~~ Considering that most of the tests for geocoders are the integration ones, I don't see much benefit from that split. #203 seems to be more viable option for improving the tests.
  - [x] ~~Deal with API keys missing in Travis builds from forks (https://github.com/geopy/geopy/pull/166#issuecomment-374197465 https://github.com/geopy/geopy/issues/74)~~ I decided to leave this as-is. See [a section in CONTRIBUTING.md](https://github.com/geopy/geopy/blob/master/CONTRIBUTING.md#geocoder-credentials)
  - [x] ~~Raise test coverage from 75% to at least 90% and fail pipeline when coverage is lower.~~ Same as the above point. Test coverage in forks is ~65%, whereas in master it's 77%. But having 90% in forks is almost impossible due to inability to test forks with credentials.
  - [x] (#297) Require linting in the Travis build pipelines (requires reformatting a significant part of the codebase, which I'm not really into right now).
  - [x] ~~Loosen some tests (they sometimes break when geocoder services responses change)~~ I do that when they start to flicker.
  - [x] (99be6fb + 1111e49) Refine CONTRIBUTING.md with info about adding new geocoders (a checklist https://github.com/geopy/geopy/pull/246#discussion_r174676830, running tests locally, refining docs [make html](https://github.com/geopy/geopy/pull/144/files#r179877877))
- [x] (#272) Add warnings for invalid input for distance routines
- [x] (#144) Include more accurate distance computation routines (`geodesic`)
- [ ] Include faster implementation of `geodesic` (See discussion at #144)
- [x] (#291) Deal with https (add SSLContext along with ability to explicitly disable TLS verification and passing own context/CAs) https://github.com/geopy/geopy/issues/124#issuecomment-294558848 https://github.com/geopy/geopy/issues/237 https://github.com/geopy/geopy/issues/212
- [x] Try to get 0 skipped tests on Travis. Some API Keys are missing right now.
- [x] (cfc14b1 efd4388 844ae3e) Pull up docstrings. Some parameters are missing, some URLs are obsolete.
- [ ] Be consistent with exceptions (i.e. always raise an appropriate one instead of a generic GeocoderServiceError)
- [x] (#317 #315) Add an ability to rate limit requests in a simple way (and automatically retry on `429 Too Many Requests`). This is especially useful for bulk-geocoding a dataset with pandas https://stackoverflow.com/q/49640197 (See also: [geopandas](https://github.com/geopandas/geopandas)) (#99)
- [x] (#288) Add some utility method for overriding a default user agent globally for all geocoders
- [x] (#319) Nominatim-based geocoders should extend Nominatim (MapQuest)
- [ ] Document a policy on geocoders' features coverage, missing parameters (#305)
- [ ] Extend the `Location` class with some new props (like bounding box, zip code, map URL). Or, perhaps, allow geocoders to return subclasses of `Location` with extra fields?

### Would be nice to have:
- [ ] (issue #268) A summary for each geocoder class (mostly around Terms of Use).
- [ ] (I'm still reasoning about this one) Add `contrib` package with some integrations. For example, a caching wrapper for Django would be great.
- [ ] CLI for both geocoding and distance computations
- [x] (#317) Add some examples to docs for usage with pandas (which [seems to be](https://stackoverflow.com/questions/tagged/geopy) a popular topic at Stack Overflow)
- [ ] Show warnings when Terms of Use are violated (added for Nominatim in #316).

See also: breaking changes plans (for geopy 2.0): #292

**Comment by cffk** [comment]
Regarding "(WIP in #144) Include faster/more accurate distance computation routines" see [my recent comment](https://github.com/geopy/geopy/pull/144#issuecomment-374047376) which advocates a simpler approach.

**Comment by umbe1987** [comment]
>  A summary for each geocoder class (mostly around Terms of Use).
I strongly support this. I started with some provider and only later found out about their TOS.
I would be happy to give my contribute to this regard.
Would this be implemented in the README?
Will it be a list of links to the official TOS of each provider (to be kept updated) or a sort of summary of the most relevant parts (e.g. cannot store geocoding results, cannot do batch geocode, and so on...).
I would be happy to contribute to this interesting project!
Thanks

**Comment by KostyaEsmukov** [comment]
@umbe1987 I created a separate issue #268 for this, so I suggest to move this discussion there.

**Comment by KostyaEsmukov** [comment]
> Try to get 0 skipped tests on Travis. Some API Keys are missing right now.

I have just added IGNFrance key to CI and that completes this long due task: now all geocoders are tested in CI: https://travis-ci.org/github/geopy/geopy/jobs/685758519. 🎉 

--

The other tasks in the roadmap which aren't complete yet are either too minor or have their separate issue, so I'm closing this.

**Comment by eadmaster** [comment]
> CLI for both geocoding and distance computations

was this added?
