### ISSUE TITLE
Version 2.0 wishlist

### ISSUE THREAD

**Issue by KostyaEsmukov** [geopy/geopy#292]
(This is a derivative from the roadmap #267 with the breaking-changes plans).

Public API cleanup:
- [x] ~Reorder the arguments in line with the base `Geocoder` class.~ (upd: not actually required because the `*` makes them kwargs, so the order doesn't matter).
- [x] Pull up the base defaults (i.e. `exactly_one=False` in some `reverse` methods, like GoogleV3, which is different from the base method default `exactly_one=True`). (deprecation warnings added in #295)
- [x] Cleanup kwargs: some are passed to constructor (i.e. Nominatim `view_box`), some to geocoding methods. There should be a consistency.
- [x] Remove `geopy.distance.vincenty` (deprecation warning added in #293)
- [x] `timeout=None` in geocoder calls should mean "no timeout". See #288

Public API changes:
- [ ] ~~Change Point `__str__` format to floats (the current one causes some confusion, e.g. https://stackoverflow.com/q/54507409)~~ (use `repr(point)` or `list(point)` instead)
- [x] Introduce async/await syntax (feasibility for 2.0 is still questionable)

Inner cleanup:
- [x] Perform all `isinstance` checks against `collections.abc` instead of `tuple`/`dict`.
- [ ] ~~Come up with a more uniform inner structure for geocoders (i.e. call response parsing functions the same name across all geocoders).~~ (would take a lot of time and bring nothing but better aesthetics)
- [x] Use a single `1.x` version in ReadTheDocs for all 1.x releases, and keep 2.x series doc in `stable`. (Also to not forget to set up redirects in RTD from old version to the new `1.x`).
- [x] Try to abstract away urllib from the base `Geocoder` class. See https://github.com/geopy/geopy/issues/149#issuecomment-136526143
- [x] Add tests to sdist (this would allow downstream package maintainers to run the test suite before packaging) (done in 1.x: 0f0ac3e030f13c804a7af7c0aa238f241bd4f589)
- [x] Add "no network calls" mode via pytest marks, which would disable integration tests (done in 1.x: #413)

Regarding dropping Python 2 support, I suggest to join the numpy/[pandas](http://pandas.pydata.org/pandas-docs/version/0.23/install.html#plan-for-dropping-python-2-7) party and drop Python 2 support after December 31, 2018. If geopy 2.0 happens to be released before that date, it should support Python 2 as well.

After dropping Python 2 support:
- [x] Make all custom geocoder params (in initializer/geocoder calls) as kwargs ([with an `*` separating kwargs from positional args in Python 3](https://stackoverflow.com/a/14298976))
- [ ] (???) Add type annotations + mypy + `py.typed` (`exactly_one`, changing the return type, might be an issue there).

After 2.0 release:
- [x] Replace unittest with pytest completely (this would probably simplify the tests and allow to extensively use pytest fixtures and marks).
- [ ] Adopt `black` formatter

Any other ideas/wishes? Except those listed in the roadmap #267.

**Comment by CatChenal** [comment]
Now that tomtom and AzureMaps geocoders are available, it would be nice to have practical (working) example.
For instance, I can retrieve the bounding boxes of (US) places and counties in Nominatim, GoogleV3, and ArcGis; I have searched hard and long to do the same with AzureMaps in vain.

* The output for qry='New York county, NY, USA' is :

 >   [Location(New York, NY, (40.71305, -74.00723, 0.0)), 
 >   Location(New York Mills, NY, (43.09643, -75.30036, 0.0)), 
 >   Location(New York Ave, Huntington, NY 11743, (40.8826, -73.41957, 0.0)), 
 >   Location(W New York Post Rd, White Plains, NY 10606, (41.02066, -73.77576, 0.0)), 
 >   Location(New York City Rd, West Hurley, NY 12491, (41.95796, -74.14314, 0.0)), 
 >   Location(NY, (40.75325, -74.00381, 0.0)), Location(New York, NY, (40.66823, -73.87839, 0.0)), 
 >   Location(Ogdensburg, NY, (44.73117, -75.42883, 0.0)), Location(NY, (42.74662, -75.77004, 0.0)), 
 >   Location(New Rochelle, NY, (40.91155, -73.78234, 0.0))]

* What's needed is a search with **structuredAddress**:
 * The county for the structured address is in the countrySecondarySubdivision field.

I have not found this info on the Azure site. Perhaps the MS people can help...

**Comment by KostyaEsmukov** [comment]
@CatChenal First of all, a geocoder improvement should be done in the 1.x line, not in 2.0, especially given that your requests do not imply any backwards-incompatible changes.

As for bounding boxes, both AzureMaps and TomTom do return them:

```
>>> r = g.geocode('New York county, NY, USA')
>>> r.raw['viewport']
{'topLeftPoint': {'lat': 40.9175, 'lon': -74.25909}, 'btmRightPoint': {'lat': 40.47738, 'lon': -73.69979}}
```

Bounding boxes are not exposed in Location (at least for now) and are supposed to be retrieved manually from the `Location.raw` attribute, so there's nothing that should be done in geopy for that.

Structured search for TomTom-based geocoders is indeed not implemented in geopy yet. Both AzureMaps [[1]] and TomTom [[2]] seem to support structured queries. I for myself don't need this functionality, but I would be happy to accept a PR which adds support for structured queries.

If you have any further questions or follow-ups -- please create a dedicate issue for that. This thread is for discussing breaking changes for geopy 2.0 specifically.

[1]: https://docs.microsoft.com/en-us/rest/api/maps/search/getsearchaddressstructured
[2]: https://developer.tomtom.com/online-search/online-search-documentation-geocoding/structured-geocode

**Comment by CatChenal** [comment]
OK, thanks a lot.

**Comment by KostyaEsmukov** [comment]
I have just updated the description with more TODO items for 2.0.

2.0 will definitely be Python >=3.5 only.

**Comment by KostyaEsmukov** [comment]
I have just pushed a pre-release to pypi:

```
pip install geopy==2.0.0rc1
```

Changelog: https://geopy.readthedocs.io/en/latest/changelog_2xx.html#v2-0-0

To try the new more effective requests adapter, install the `requests` library:

```
pip install 'geopy[requests]==2.0.0rc1'
```

I'll wait for a week for any feedback, and if there won't be any issues, I will release 2.0.0.

**Comment by KostyaEsmukov** [comment]
geopy 2.0 has finally been released 🎉 

```
pip install geopy==2.0.0
```

Changelog: https://geopy.readthedocs.io/en/stable/changelog_2xx.html#v2-0-0

Changes since 2.0.0rc1: https://github.com/geopy/geopy/compare/2.0.0rc1...2.0.0
